# Generated by Django 5.1 on 2024-08-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('publishing', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('rack_number', models.IntegerField()),
                ('number_of_copies', models.IntegerField()),
                ('discounted_price', models.FloatField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id_discount', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_discount', models.CharField(max_length=100, unique=True)),
                ('discount_percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_genre', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('author_last_name', models.CharField(max_length=25)),
                ('author_first_name', models.CharField(max_length=25)),
                ('author_patronymic', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'unique_together': {('author_last_name', 'author_first_name', 'author_patronymic')},
            },
        ),
        migrations.CreateModel(
            name='BookNumber',
            fields=[
                ('book_number', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='id_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discount'),
        ),
        migrations.AddField(
            model_name='book',
            name='id_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id_seller', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25, unique=True)),
                ('password_hash', models.CharField(max_length=255, unique=True)),
                ('salt', models.CharField(max_length=255, unique=True)),
                ('seller_last_name', models.CharField(max_length=25)),
                ('seller_first_name', models.CharField(max_length=25)),
                ('seller_patronymic', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('date_of_last_authorization', models.DateField(auto_now=True)),
                ('date_of_last_deauthorization', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('password_hash', 'salt')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('book_number', models.CharField(max_length=17, unique=True)),
                ('date_of_sale', models.DateField(auto_now=True)),
                ('price_of_sale', models.FloatField()),
                ('id_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seller')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsOfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
            ],
            options={
                'unique_together': {('id_author', 'id_book')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('id_genre', 'title', 'publishing')},
        ),
    ]
