# Generated by Django 5.1 on 2024-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
