# Generated by Django 5.1 on 2024-08-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='book_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booknumber'),
        ),
    ]
