# Generated by Django 5.1 on 2024-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sale_book_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_copies',
            field=models.IntegerField(default=0),
        ),
    ]
