# Generated by Django 5.1 on 2024-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_number_of_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
    ]
