# Generated by Django 5.1 on 2024-09-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_book_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknumber',
            name='status',
            field=models.CharField(default='Не продан', max_length=10),
        ),
    ]
