# Generated by Django 5.1 on 2024-09-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booknumber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='book_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booknumber', unique=True),
        ),
    ]
